server:
  port: 8080
#spring
spring:
  devtools:
    restart:
      enabled: false
  application:
      name: crud-example
  #mvc
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  mvc:
    date-format: yyyy-MM-dd HH\:mm\:ss
  # H2 DATABASE CONFIG
# jdbc_config   datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zzfw_data_center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: data_center
    password: data_center
# Hikari will use the above plus the following to setup connection pooling
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#mybatis
mybatis-plus:
  mapper-locations: classpath:/com/lhy.example/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lhy.example.*.entity
#  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #打印sql语句,调试用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  enabled: true
  title: sking-admin
  description: 后台管理服务端
  version: 1.0.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: http://blog.csdn.net/v2sking
  contact.name: 再见尼罗河
  contact.url: http://blog.csdn.net/v2sking
  contact.email: 1591963820@163.com
  base-package: com.lhy
  base-path: /**
  exclude-path: /error, /ops/**
  docket:
    user:
      title: 用户
      description: 用户相关
      base-path: /sys/sp-user/**
